sudo: required
services:
  - docker

before_install:
  - docker build -t hungpmpercy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hungpmpercy/docker-react npm run test -- --coverage
