sudo: required
branches:
  - master

services:
  - docker

before_install:
  - docker build -t hungpmpercy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hungpmpercy/docker-react npm run test -- --coverage
# # Note that those keys are defined in travis website
# deploy:
#   provider: eslasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-32110501561"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
